main = input("Stronkfish Brand Calculator\n\nAddition = a\nSubtraction = b\nMultiplication = c\nDivision = d\n\n") # Selecting Operation (1)
if main.upper() == "A": # Calculation (2-21)
    print("\nOperation: Addition\n")
    a = float(input("First Number: "))
    b = float(input("Second Number: "))
    print(f"\nAnswer: {a + b}")
if main == "b":
    print("\nOperation: Subtraction\n")
    a = float(input("First Number: "))
    b = float(input("Second Number: "))
    print(f"\nAnswer: {a - b}")
if main == "c":
    print("\nOperation: Multiplication\n")
    a = float(input("First Number: "))
    b = float(input("Second Number: "))
    print(f"\nAnswer: {a * b}")
if main == "d":
    print("\nOperation: Division\n")
    a = float(input("First Number: "))
    b = float(input("Second Number: "))
    print(f"\nAnswer: {a / b}")
