main = input("Stonkfish Brand MPH/KPH Converter\n\nMPH = Convert KPH to MPH\nKPH = Convert MPH TO KPH\n\n") # Choose Conversion MPH or KPH (1)
conv = "" # Pre-Define (2)
if main.upper() == "MPH": # KPH to MPH Conversion (3-5)
    conv = float(input("\nEnter the speed in KPH to convert it into MPH: "))
    print(f"\nKPH: {conv}\nMPH: {conv*0.6214}\n")
if main.upper() == "KPH": # MPH to KPH Conversion (6-8)
    conv = float(input("\nEnter the speed in MPH to convert it into KPH: "))
    print(f"\nMPH: {conv}\nKPH: {conv*1.6093}\n")
